### ISSUE TITLE
JS VM errors halting execution, preventing results from other tests

### ISSUE THREAD

**Issue by sebasslash** [Serdnad/yester#2]
If the JS VM throws an exception, it should only fail for the respective test. This is an example:

```bash
2021/07/13 12:38:45 TypeError: Cannot access member '0' of undefined
```

I should still see if other tests have passed/failed. Something like:

```bash
3/4 Tests Passed
FAILED [testX]: Body Validation Error: Type Error: Cannot access member '0' of undefined
```

**Comment by Serdnad** [comment]
Fixed in v1.0.1 by [this](https://github.com/Serdnad/yester/commit/01222a9c089ddec96143dffd8856cf9a98de3a15) commit.
